Update index.go
mickael-kerjean/filestash pull request #715
Opened 2024-07-18 07:03 UTC by zemzema

Enable/Disable edit of document via OnlyOffice API.

2024-07-22 21:26 UTC, mickael-kerjean requested changes

2024-07-22 21:26 UTC, mickael-kerjean commented on server/plugin/plg_editor_onlyoffice/index.go
> +		f.Id = "onlyoffice_can_edit"
The id should be in the "plugin_enable" Target attribute so it is only shown when only office is enabled

2024-07-23 06:39 UTC, zemzema commented
Fixed!

2024-07-23 08:56 UTC, mickael-kerjean approved these changes

2024-07-23 08:56 UTC, merged